// GENERATED by tool/gen_tokens.py -- do not edit by hand.
//
// Run `python3 tool/gen_tokens.py` after changing a token, or edit the spec
// there. Hand-maintained edits to the classes below WILL be overwritten.

import 'package:flutter/material.dart';

/// Brand identity: the purple/gold/ink core every other token is mixed from.
@immutable
class BrandColors {
  const BrandColors({
    required this.primary,
    required this.onPrimary,
    required this.primaryDeep,
    required this.primaryWash,
    required this.accent,
    required this.accentDeep,
    required this.ink,
  });

  /// Primary brand purple. Drives selection rings, active nav, key accents.
  final Color primary;

  /// Legible content drawn on top of [primary].
  final Color onPrimary;

  /// Pressed / recessed variant of [primary].
  final Color primaryDeep;

  /// Base hue for low-alpha primary washes. Callers apply their own alpha.
  final Color primaryWash;

  /// Gold accent. Bubble/analysis highlights, streak markers.
  final Color accent;

  /// Legible gold for text on light surfaces.
  final Color accentDeep;

  /// Deepest brand ink. Headline text on light surfaces.
  final Color ink;

  BrandColors copyWith({
    Color? primary,
    Color? onPrimary,
    Color? primaryDeep,
    Color? primaryWash,
    Color? accent,
    Color? accentDeep,
    Color? ink,
  }) => BrandColors(
    primary: primary ?? this.primary,
    onPrimary: onPrimary ?? this.onPrimary,
    primaryDeep: primaryDeep ?? this.primaryDeep,
    primaryWash: primaryWash ?? this.primaryWash,
    accent: accent ?? this.accent,
    accentDeep: accentDeep ?? this.accentDeep,
    ink: ink ?? this.ink,
  );

  static BrandColors lerp(BrandColors a, BrandColors b, double t) =>
      BrandColors(
        primary: Color.lerp(a.primary, b.primary, t)!,
        onPrimary: Color.lerp(a.onPrimary, b.onPrimary, t)!,
        primaryDeep: Color.lerp(a.primaryDeep, b.primaryDeep, t)!,
        primaryWash: Color.lerp(a.primaryWash, b.primaryWash, t)!,
        accent: Color.lerp(a.accent, b.accent, t)!,
        accentDeep: Color.lerp(a.accentDeep, b.accentDeep, t)!,
        ink: Color.lerp(a.ink, b.ink, t)!,
      );

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is BrandColors &&
        primary == other.primary &&
        onPrimary == other.onPrimary &&
        primaryDeep == other.primaryDeep &&
        primaryWash == other.primaryWash &&
        accent == other.accent &&
        accentDeep == other.accentDeep &&
        ink == other.ink;
  }

  @override
  int get hashCode => Object.hashAll([
    primary,
    onPrimary,
    primaryDeep,
    primaryWash,
    accent,
    accentDeep,
    ink,
  ]);

  /// Every token in this group, by name.
  /// ///
  /// /// Used by the theming tests to prove [copyWith] touches only the field
  /// /// it was given, and handy for dumping or diffing a palette.
  Map<String, Color> get asMap => {
    'primary': primary,
    'onPrimary': onPrimary,
    'primaryDeep': primaryDeep,
    'primaryWash': primaryWash,
    'accent': accent,
    'accentDeep': accentDeep,
    'ink': ink,
  };
}

/// Layered background planes. Roles, not appearances: `raised` is whatever
/// /// sits above `canvas` in that brightness.
@immutable
class SurfaceColors {
  const SurfaceColors({
    required this.canvas,
    required this.raised,
    required this.sunken,
    required this.overlay,
    required this.outline,
    required this.outlineStrong,
    required this.scrim,
    required this.cardSurface,
    required this.cardSurfaceRaised,
    required this.cardSurfaceSelected,
    required this.chipOnCard,
    required this.hub,
    required this.pill,
  });

  /// App background, furthest plane.
  final Color canvas;

  /// Cards and sheets sitting on [canvas].
  final Color raised;

  /// Inset wells: metric chips, segmented control tracks.
  final Color sunken;

  /// Small filled chips (tags, severity pills).
  final Color overlay;

  /// Default hairline border.
  final Color outline;

  /// Emphasised border: active inputs, selected cards.
  final Color outlineStrong;

  /// Base black behind modal barriers. Callers apply alpha.
  final Color scrim;

  /// Note/bubble card. Dark card on a light page by design.
  final Color cardSurface;

  /// Menus and headers sitting on [cardSurface].
  final Color cardSurfaceRaised;

  /// Selected note card.
  final Color cardSurfaceSelected;

  /// Translucent-white chip fill composited onto [cardSurface].
  final Color chipOnCard;

  /// Radial dial hub backing and readout pills.
  final Color hub;

  /// Floating chip background (hex toggle, etc).
  final Color pill;

  SurfaceColors copyWith({
    Color? canvas,
    Color? raised,
    Color? sunken,
    Color? overlay,
    Color? outline,
    Color? outlineStrong,
    Color? scrim,
    Color? cardSurface,
    Color? cardSurfaceRaised,
    Color? cardSurfaceSelected,
    Color? chipOnCard,
    Color? hub,
    Color? pill,
  }) => SurfaceColors(
    canvas: canvas ?? this.canvas,
    raised: raised ?? this.raised,
    sunken: sunken ?? this.sunken,
    overlay: overlay ?? this.overlay,
    outline: outline ?? this.outline,
    outlineStrong: outlineStrong ?? this.outlineStrong,
    scrim: scrim ?? this.scrim,
    cardSurface: cardSurface ?? this.cardSurface,
    cardSurfaceRaised: cardSurfaceRaised ?? this.cardSurfaceRaised,
    cardSurfaceSelected: cardSurfaceSelected ?? this.cardSurfaceSelected,
    chipOnCard: chipOnCard ?? this.chipOnCard,
    hub: hub ?? this.hub,
    pill: pill ?? this.pill,
  );

  static SurfaceColors lerp(SurfaceColors a, SurfaceColors b, double t) =>
      SurfaceColors(
        canvas: Color.lerp(a.canvas, b.canvas, t)!,
        raised: Color.lerp(a.raised, b.raised, t)!,
        sunken: Color.lerp(a.sunken, b.sunken, t)!,
        overlay: Color.lerp(a.overlay, b.overlay, t)!,
        outline: Color.lerp(a.outline, b.outline, t)!,
        outlineStrong: Color.lerp(a.outlineStrong, b.outlineStrong, t)!,
        scrim: Color.lerp(a.scrim, b.scrim, t)!,
        cardSurface: Color.lerp(a.cardSurface, b.cardSurface, t)!,
        cardSurfaceRaised:
            Color.lerp(a.cardSurfaceRaised, b.cardSurfaceRaised, t)!,
        cardSurfaceSelected:
            Color.lerp(a.cardSurfaceSelected, b.cardSurfaceSelected, t)!,
        chipOnCard: Color.lerp(a.chipOnCard, b.chipOnCard, t)!,
        hub: Color.lerp(a.hub, b.hub, t)!,
        pill: Color.lerp(a.pill, b.pill, t)!,
      );

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is SurfaceColors &&
        canvas == other.canvas &&
        raised == other.raised &&
        sunken == other.sunken &&
        overlay == other.overlay &&
        outline == other.outline &&
        outlineStrong == other.outlineStrong &&
        scrim == other.scrim &&
        cardSurface == other.cardSurface &&
        cardSurfaceRaised == other.cardSurfaceRaised &&
        cardSurfaceSelected == other.cardSurfaceSelected &&
        chipOnCard == other.chipOnCard &&
        hub == other.hub &&
        pill == other.pill;
  }

  @override
  int get hashCode => Object.hashAll([
    canvas,
    raised,
    sunken,
    overlay,
    outline,
    outlineStrong,
    scrim,
    cardSurface,
    cardSurfaceRaised,
    cardSurfaceSelected,
    chipOnCard,
    hub,
    pill,
  ]);

  /// Every token in this group, by name.
  /// ///
  /// /// Used by the theming tests to prove [copyWith] touches only the field
  /// /// it was given, and handy for dumping or diffing a palette.
  Map<String, Color> get asMap => {
    'canvas': canvas,
    'raised': raised,
    'sunken': sunken,
    'overlay': overlay,
    'outline': outline,
    'outlineStrong': outlineStrong,
    'scrim': scrim,
    'cardSurface': cardSurface,
    'cardSurfaceRaised': cardSurfaceRaised,
    'cardSurfaceSelected': cardSurfaceSelected,
    'chipOnCard': chipOnCard,
    'hub': hub,
    'pill': pill,
  };
}

/// Elevation shadows. Alpha is baked in so callers never hand-roll
/// /// `Colors.black.withValues(alpha: 0.06)`.
@immutable
class ShadowColors {
  const ShadowColors({
    required this.soft,
    required this.strong,
    required this.scrim,
    required this.ring,
  });

  /// Resting card shadow.
  final Color soft;

  /// Raised sheet / dialog shadow.
  final Color strong;

  /// Modal barrier.
  final Color scrim;

  /// Selected-state border wash.
  final Color ring;

  ShadowColors copyWith({
    Color? soft,
    Color? strong,
    Color? scrim,
    Color? ring,
  }) => ShadowColors(
    soft: soft ?? this.soft,
    strong: strong ?? this.strong,
    scrim: scrim ?? this.scrim,
    ring: ring ?? this.ring,
  );

  static ShadowColors lerp(ShadowColors a, ShadowColors b, double t) =>
      ShadowColors(
        soft: Color.lerp(a.soft, b.soft, t)!,
        strong: Color.lerp(a.strong, b.strong, t)!,
        scrim: Color.lerp(a.scrim, b.scrim, t)!,
        ring: Color.lerp(a.ring, b.ring, t)!,
      );

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is ShadowColors &&
        soft == other.soft &&
        strong == other.strong &&
        scrim == other.scrim &&
        ring == other.ring;
  }

  @override
  int get hashCode => Object.hashAll([soft, strong, scrim, ring]);

  /// Every token in this group, by name.
  /// ///
  /// /// Used by the theming tests to prove [copyWith] touches only the field
  /// /// it was given, and handy for dumping or diffing a palette.
  Map<String, Color> get asMap => {
    'soft': soft,
    'strong': strong,
    'scrim': scrim,
    'ring': ring,
  };
}

/// Foreground roles. The `onDark*` family is for content drawn on
/// /// [SurfaceColors.cardSurface], which stays dark in both brightnesses.
@immutable
class TextColors {
  const TextColors({
    required this.strong,
    required this.body,
    required this.muted,
    required this.faint,
    required this.disabled,
    required this.onAccent,
    required this.onBrand,
    required this.onModeBadge,
    required this.onDark,
    required this.onDarkMuted,
    required this.onDarkFaint,
    required this.onDarkIcon,
  });

  /// Primary body and heading text.
  final Color strong;

  /// Secondary body text.
  final Color body;

  /// Helper/caption text. Replaces Colors.black54 on light.
  final Color muted;

  /// Tertiary text, timestamps. Replaces Colors.black45.
  final Color faint;

  /// Non-interactive text. Replaces Colors.black38.
  final Color disabled;

  /// Text on [BrandColors.accent] fills.
  final Color onAccent;

  /// Text/icon on a [BrandColors.primary] or other saturated fill. The brand purple is dark enough in both brightnesses to keep white.
  final Color onBrand;

  /// Label on an [EditorColors] mode badge. The mode hues run light (yellow/green), so the badge needs ink, not white.
  final Color onModeBadge;

  /// Primary text on a dark card.
  final Color onDark;

  /// Secondary text on a dark card. Composited white 60%.
  final Color onDarkMuted;

  /// Tertiary text on a dark card. Composited white 54%.
  final Color onDarkFaint;

  /// Icon on a dark card. Composited white 70%.
  final Color onDarkIcon;

  TextColors copyWith({
    Color? strong,
    Color? body,
    Color? muted,
    Color? faint,
    Color? disabled,
    Color? onAccent,
    Color? onBrand,
    Color? onModeBadge,
    Color? onDark,
    Color? onDarkMuted,
    Color? onDarkFaint,
    Color? onDarkIcon,
  }) => TextColors(
    strong: strong ?? this.strong,
    body: body ?? this.body,
    muted: muted ?? this.muted,
    faint: faint ?? this.faint,
    disabled: disabled ?? this.disabled,
    onAccent: onAccent ?? this.onAccent,
    onBrand: onBrand ?? this.onBrand,
    onModeBadge: onModeBadge ?? this.onModeBadge,
    onDark: onDark ?? this.onDark,
    onDarkMuted: onDarkMuted ?? this.onDarkMuted,
    onDarkFaint: onDarkFaint ?? this.onDarkFaint,
    onDarkIcon: onDarkIcon ?? this.onDarkIcon,
  );

  static TextColors lerp(TextColors a, TextColors b, double t) => TextColors(
    strong: Color.lerp(a.strong, b.strong, t)!,
    body: Color.lerp(a.body, b.body, t)!,
    muted: Color.lerp(a.muted, b.muted, t)!,
    faint: Color.lerp(a.faint, b.faint, t)!,
    disabled: Color.lerp(a.disabled, b.disabled, t)!,
    onAccent: Color.lerp(a.onAccent, b.onAccent, t)!,
    onBrand: Color.lerp(a.onBrand, b.onBrand, t)!,
    onModeBadge: Color.lerp(a.onModeBadge, b.onModeBadge, t)!,
    onDark: Color.lerp(a.onDark, b.onDark, t)!,
    onDarkMuted: Color.lerp(a.onDarkMuted, b.onDarkMuted, t)!,
    onDarkFaint: Color.lerp(a.onDarkFaint, b.onDarkFaint, t)!,
    onDarkIcon: Color.lerp(a.onDarkIcon, b.onDarkIcon, t)!,
  );

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is TextColors &&
        strong == other.strong &&
        body == other.body &&
        muted == other.muted &&
        faint == other.faint &&
        disabled == other.disabled &&
        onAccent == other.onAccent &&
        onBrand == other.onBrand &&
        onModeBadge == other.onModeBadge &&
        onDark == other.onDark &&
        onDarkMuted == other.onDarkMuted &&
        onDarkFaint == other.onDarkFaint &&
        onDarkIcon == other.onDarkIcon;
  }

  @override
  int get hashCode => Object.hashAll([
    strong,
    body,
    muted,
    faint,
    disabled,
    onAccent,
    onBrand,
    onModeBadge,
    onDark,
    onDarkMuted,
    onDarkFaint,
    onDarkIcon,
  ]);

  /// Every token in this group, by name.
  /// ///
  /// /// Used by the theming tests to prove [copyWith] touches only the field
  /// /// it was given, and handy for dumping or diffing a palette.
  Map<String, Color> get asMap => {
    'strong': strong,
    'body': body,
    'muted': muted,
    'faint': faint,
    'disabled': disabled,
    'onAccent': onAccent,
    'onBrand': onBrand,
    'onModeBadge': onModeBadge,
    'onDark': onDark,
    'onDarkMuted': onDarkMuted,
    'onDarkFaint': onDarkFaint,
    'onDarkIcon': onDarkIcon,
  };
}

/// Semantic state ramp. Each state exposes three roles: `surface` for a
/// /// filled background, `strong` for legible text/icon, and the base for accents.
@immutable
class StatusColors {
  const StatusColors({
    required this.success,
    required this.successStrong,
    required this.successSurface,
    required this.successSoft,
    required this.warning,
    required this.warningStrong,
    required this.warningSurface,
    required this.warningSoft,
    required this.danger,
    required this.dangerDeep,
    required this.dangerStrong,
    required this.dangerSoft,
    required this.dangerSurface,
    required this.info,
    required this.infoSurface,
    required this.neutral,
    required this.neutralStrong,
    required this.neutralSurface,
    required this.neutralSoft,
  });

  /// Success / complete / graded.
  final Color success;

  /// Success text and icons on [successSurface].
  final Color successStrong;

  /// Success background fill.
  final Color successSurface;

  /// Decorative success accent.
  final Color successSoft;

  /// Warning / stale / queued.
  final Color warning;

  /// Warning text and icons on [warningSurface].
  final Color warningStrong;

  /// Warning background fill.
  final Color warningSurface;

  /// Decorative warning accent.
  final Color warningSoft;

  /// Error / destructive accent.
  final Color danger;

  /// High-emphasis danger. Priority cards, overdue counts.
  final Color dangerDeep;

  /// Danger text and icons on [dangerSurface].
  final Color dangerStrong;

  /// Decorative danger accent.
  final Color dangerSoft;

  /// Danger background fill.
  final Color dangerSurface;

  /// Informational / selected accent.
  final Color info;

  /// Informational background fill.
  final Color infoSurface;

  /// Neutral / off / archived.
  final Color neutral;

  /// Neutral text and icons on [neutralSurface].
  final Color neutralStrong;

  /// Neutral background fill.
  final Color neutralSurface;

  /// Decorative neutral: study-bubble state rings, neutral badges.
  final Color neutralSoft;

  StatusColors copyWith({
    Color? success,
    Color? successStrong,
    Color? successSurface,
    Color? successSoft,
    Color? warning,
    Color? warningStrong,
    Color? warningSurface,
    Color? warningSoft,
    Color? danger,
    Color? dangerDeep,
    Color? dangerStrong,
    Color? dangerSoft,
    Color? dangerSurface,
    Color? info,
    Color? infoSurface,
    Color? neutral,
    Color? neutralStrong,
    Color? neutralSurface,
    Color? neutralSoft,
  }) => StatusColors(
    success: success ?? this.success,
    successStrong: successStrong ?? this.successStrong,
    successSurface: successSurface ?? this.successSurface,
    successSoft: successSoft ?? this.successSoft,
    warning: warning ?? this.warning,
    warningStrong: warningStrong ?? this.warningStrong,
    warningSurface: warningSurface ?? this.warningSurface,
    warningSoft: warningSoft ?? this.warningSoft,
    danger: danger ?? this.danger,
    dangerDeep: dangerDeep ?? this.dangerDeep,
    dangerStrong: dangerStrong ?? this.dangerStrong,
    dangerSoft: dangerSoft ?? this.dangerSoft,
    dangerSurface: dangerSurface ?? this.dangerSurface,
    info: info ?? this.info,
    infoSurface: infoSurface ?? this.infoSurface,
    neutral: neutral ?? this.neutral,
    neutralStrong: neutralStrong ?? this.neutralStrong,
    neutralSurface: neutralSurface ?? this.neutralSurface,
    neutralSoft: neutralSoft ?? this.neutralSoft,
  );

  static StatusColors lerp(StatusColors a, StatusColors b, double t) =>
      StatusColors(
        success: Color.lerp(a.success, b.success, t)!,
        successStrong: Color.lerp(a.successStrong, b.successStrong, t)!,
        successSurface: Color.lerp(a.successSurface, b.successSurface, t)!,
        successSoft: Color.lerp(a.successSoft, b.successSoft, t)!,
        warning: Color.lerp(a.warning, b.warning, t)!,
        warningStrong: Color.lerp(a.warningStrong, b.warningStrong, t)!,
        warningSurface: Color.lerp(a.warningSurface, b.warningSurface, t)!,
        warningSoft: Color.lerp(a.warningSoft, b.warningSoft, t)!,
        danger: Color.lerp(a.danger, b.danger, t)!,
        dangerDeep: Color.lerp(a.dangerDeep, b.dangerDeep, t)!,
        dangerStrong: Color.lerp(a.dangerStrong, b.dangerStrong, t)!,
        dangerSoft: Color.lerp(a.dangerSoft, b.dangerSoft, t)!,
        dangerSurface: Color.lerp(a.dangerSurface, b.dangerSurface, t)!,
        info: Color.lerp(a.info, b.info, t)!,
        infoSurface: Color.lerp(a.infoSurface, b.infoSurface, t)!,
        neutral: Color.lerp(a.neutral, b.neutral, t)!,
        neutralStrong: Color.lerp(a.neutralStrong, b.neutralStrong, t)!,
        neutralSurface: Color.lerp(a.neutralSurface, b.neutralSurface, t)!,
        neutralSoft: Color.lerp(a.neutralSoft, b.neutralSoft, t)!,
      );

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is StatusColors &&
        success == other.success &&
        successStrong == other.successStrong &&
        successSurface == other.successSurface &&
        successSoft == other.successSoft &&
        warning == other.warning &&
        warningStrong == other.warningStrong &&
        warningSurface == other.warningSurface &&
        warningSoft == other.warningSoft &&
        danger == other.danger &&
        dangerDeep == other.dangerDeep &&
        dangerStrong == other.dangerStrong &&
        dangerSoft == other.dangerSoft &&
        dangerSurface == other.dangerSurface &&
        info == other.info &&
        infoSurface == other.infoSurface &&
        neutral == other.neutral &&
        neutralStrong == other.neutralStrong &&
        neutralSurface == other.neutralSurface &&
        neutralSoft == other.neutralSoft;
  }

  @override
  int get hashCode => Object.hashAll([
    success,
    successStrong,
    successSurface,
    successSoft,
    warning,
    warningStrong,
    warningSurface,
    warningSoft,
    danger,
    dangerDeep,
    dangerStrong,
    dangerSoft,
    dangerSurface,
    info,
    infoSurface,
    neutral,
    neutralStrong,
    neutralSurface,
    neutralSoft,
  ]);

  /// Every token in this group, by name.
  /// ///
  /// /// Used by the theming tests to prove [copyWith] touches only the field
  /// /// it was given, and handy for dumping or diffing a palette.
  Map<String, Color> get asMap => {
    'success': success,
    'successStrong': successStrong,
    'successSurface': successSurface,
    'successSoft': successSoft,
    'warning': warning,
    'warningStrong': warningStrong,
    'warningSurface': warningSurface,
    'warningSoft': warningSoft,
    'danger': danger,
    'dangerDeep': dangerDeep,
    'dangerStrong': dangerStrong,
    'dangerSoft': dangerSoft,
    'dangerSurface': dangerSurface,
    'info': info,
    'infoSurface': infoSurface,
    'neutral': neutral,
    'neutralStrong': neutralStrong,
    'neutralSurface': neutralSurface,
    'neutralSoft': neutralSoft,
  };
}

/// Code block chrome, pinned to the One Dark family. These are dark in
/// /// both brightnesses because a syntax theme is a product decision, not a
/// /// brightness mirror.
@immutable
class CodeColors {
  const CodeColors({
    required this.background,
    required this.header,
    required this.headerBorder,
    required this.onCode,
    required this.onCodeMuted,
    required this.gutterText,
    required this.textDefault,
    required this.selection,
  });

  /// Code block body.
  final Color background;

  /// Code block header / language picker.
  final Color header;

  /// Divider under the code header.
  final Color headerBorder;

  /// Default code text.
  final Color onCode;

  /// Secondary code text and icons.
  final Color onCodeMuted;

  /// Line numbers and quickview chrome.
  final Color gutterText;

  /// Editor body text when no explicit colour is set.
  final Color textDefault;

  /// Selection highlight inside the editor.
  final Color selection;

  CodeColors copyWith({
    Color? background,
    Color? header,
    Color? headerBorder,
    Color? onCode,
    Color? onCodeMuted,
    Color? gutterText,
    Color? textDefault,
    Color? selection,
  }) => CodeColors(
    background: background ?? this.background,
    header: header ?? this.header,
    headerBorder: headerBorder ?? this.headerBorder,
    onCode: onCode ?? this.onCode,
    onCodeMuted: onCodeMuted ?? this.onCodeMuted,
    gutterText: gutterText ?? this.gutterText,
    textDefault: textDefault ?? this.textDefault,
    selection: selection ?? this.selection,
  );

  static CodeColors lerp(CodeColors a, CodeColors b, double t) => CodeColors(
    background: Color.lerp(a.background, b.background, t)!,
    header: Color.lerp(a.header, b.header, t)!,
    headerBorder: Color.lerp(a.headerBorder, b.headerBorder, t)!,
    onCode: Color.lerp(a.onCode, b.onCode, t)!,
    onCodeMuted: Color.lerp(a.onCodeMuted, b.onCodeMuted, t)!,
    gutterText: Color.lerp(a.gutterText, b.gutterText, t)!,
    textDefault: Color.lerp(a.textDefault, b.textDefault, t)!,
    selection: Color.lerp(a.selection, b.selection, t)!,
  );

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is CodeColors &&
        background == other.background &&
        header == other.header &&
        headerBorder == other.headerBorder &&
        onCode == other.onCode &&
        onCodeMuted == other.onCodeMuted &&
        gutterText == other.gutterText &&
        textDefault == other.textDefault &&
        selection == other.selection;
  }

  @override
  int get hashCode => Object.hashAll([
    background,
    header,
    headerBorder,
    onCode,
    onCodeMuted,
    gutterText,
    textDefault,
    selection,
  ]);

  /// Every token in this group, by name.
  /// ///
  /// /// Used by the theming tests to prove [copyWith] touches only the field
  /// /// it was given, and handy for dumping or diffing a palette.
  Map<String, Color> get asMap => {
    'background': background,
    'header': header,
    'headerBorder': headerBorder,
    'onCode': onCode,
    'onCodeMuted': onCodeMuted,
    'gutterText': gutterText,
    'textDefault': textDefault,
    'selection': selection,
  };
}
