// GENERATED by tool/gen_tokens.py -- do not edit by hand.
//
// Run `python3 tool/gen_tokens.py` after changing a token, or edit the spec
// there. Hand-maintained edits to the classes below WILL be overwritten.

import 'package:flutter/material.dart';

/// Editor, vim modes, and page chrome.
/// ///
/// /// The four mode tokens are deliberately separate even where the default
/// /// theme gives them equal values, so a custom theme can diverge them.
@immutable
class EditorColors {
  const EditorColors({
    required this.insertMode,
    required this.normalMode,
    required this.analysisMode,
    required this.analysisBlock,
    required this.modeBadgeInsert,
    required this.modeBadgeNormal,
    required this.modeBadgeAnalysis,
    required this.pageBorder,
    required this.pageShadow,
    required this.pageShadowSoft,
    required this.staleTint,
    required this.analysisTint,
    required this.staleBadge,
    required this.analysisBadge,
    required this.savedBadge,
    required this.unsavedBadge,
    required this.neutralBadge,
    required this.linkColor,
    required this.selection,
    required this.blockquoteBar,
    required this.eraserFill,
    required this.eraserStroke,
    required this.penDefault,
  });

  /// Vim insert mode accent.
  final Color insertMode;

  /// Vim normal mode accent.
  final Color normalMode;

  /// Vim analysis mode accent.
  final Color analysisMode;

  /// Block tint while in analysis mode.
  final Color analysisBlock;

  /// Mode chip fill when in insert mode.
  final Color modeBadgeInsert;

  /// Mode chip fill when in normal mode.
  final Color modeBadgeNormal;

  /// Mode chip fill when in analysis mode.
  final Color modeBadgeAnalysis;

  /// Page outline.
  final Color pageBorder;

  /// Drop shadow under a page.
  final Color pageShadow;

  /// Ambient shadow under a page.
  final Color pageShadowSoft;

  /// Page wash when the analysis is stale.
  final Color staleTint;

  /// Page wash while analysis is in flight.
  final Color analysisTint;

  /// Stale-state icon and label.
  final Color staleBadge;

  /// In-flight analysis icon and label.
  final Color analysisBadge;

  /// Saved-state dot and label.
  final Color savedBadge;

  /// Unsaved-state dot and label.
  final Color unsavedBadge;

  /// Neutral-state dot and label.
  final Color neutralBadge;

  /// Rendered link text.
  final Color linkColor;

  /// Text selection highlight.
  final Color selection;

  /// Accent bar down the left of a blockquote.
  final Color blockquoteBar;

  /// Filled body of the eraser cursor ring.
  final Color eraserFill;

  /// Outline of the eraser cursor ring.
  final Color eraserStroke;

  /// Ink colour for the annotator's freehand pen.
  final Color penDefault;

  EditorColors copyWith({
    Color? insertMode,
    Color? normalMode,
    Color? analysisMode,
    Color? analysisBlock,
    Color? modeBadgeInsert,
    Color? modeBadgeNormal,
    Color? modeBadgeAnalysis,
    Color? pageBorder,
    Color? pageShadow,
    Color? pageShadowSoft,
    Color? staleTint,
    Color? analysisTint,
    Color? staleBadge,
    Color? analysisBadge,
    Color? savedBadge,
    Color? unsavedBadge,
    Color? neutralBadge,
    Color? linkColor,
    Color? selection,
    Color? blockquoteBar,
    Color? eraserFill,
    Color? eraserStroke,
    Color? penDefault,
  }) => EditorColors(
    insertMode: insertMode ?? this.insertMode,
    normalMode: normalMode ?? this.normalMode,
    analysisMode: analysisMode ?? this.analysisMode,
    analysisBlock: analysisBlock ?? this.analysisBlock,
    modeBadgeInsert: modeBadgeInsert ?? this.modeBadgeInsert,
    modeBadgeNormal: modeBadgeNormal ?? this.modeBadgeNormal,
    modeBadgeAnalysis: modeBadgeAnalysis ?? this.modeBadgeAnalysis,
    pageBorder: pageBorder ?? this.pageBorder,
    pageShadow: pageShadow ?? this.pageShadow,
    pageShadowSoft: pageShadowSoft ?? this.pageShadowSoft,
    staleTint: staleTint ?? this.staleTint,
    analysisTint: analysisTint ?? this.analysisTint,
    staleBadge: staleBadge ?? this.staleBadge,
    analysisBadge: analysisBadge ?? this.analysisBadge,
    savedBadge: savedBadge ?? this.savedBadge,
    unsavedBadge: unsavedBadge ?? this.unsavedBadge,
    neutralBadge: neutralBadge ?? this.neutralBadge,
    linkColor: linkColor ?? this.linkColor,
    selection: selection ?? this.selection,
    blockquoteBar: blockquoteBar ?? this.blockquoteBar,
    eraserFill: eraserFill ?? this.eraserFill,
    eraserStroke: eraserStroke ?? this.eraserStroke,
    penDefault: penDefault ?? this.penDefault,
  );

  static EditorColors lerp(EditorColors a, EditorColors b, double t) =>
      EditorColors(
        insertMode: Color.lerp(a.insertMode, b.insertMode, t)!,
        normalMode: Color.lerp(a.normalMode, b.normalMode, t)!,
        analysisMode: Color.lerp(a.analysisMode, b.analysisMode, t)!,
        analysisBlock: Color.lerp(a.analysisBlock, b.analysisBlock, t)!,
        modeBadgeInsert: Color.lerp(a.modeBadgeInsert, b.modeBadgeInsert, t)!,
        modeBadgeNormal: Color.lerp(a.modeBadgeNormal, b.modeBadgeNormal, t)!,
        modeBadgeAnalysis:
            Color.lerp(a.modeBadgeAnalysis, b.modeBadgeAnalysis, t)!,
        pageBorder: Color.lerp(a.pageBorder, b.pageBorder, t)!,
        pageShadow: Color.lerp(a.pageShadow, b.pageShadow, t)!,
        pageShadowSoft: Color.lerp(a.pageShadowSoft, b.pageShadowSoft, t)!,
        staleTint: Color.lerp(a.staleTint, b.staleTint, t)!,
        analysisTint: Color.lerp(a.analysisTint, b.analysisTint, t)!,
        staleBadge: Color.lerp(a.staleBadge, b.staleBadge, t)!,
        analysisBadge: Color.lerp(a.analysisBadge, b.analysisBadge, t)!,
        savedBadge: Color.lerp(a.savedBadge, b.savedBadge, t)!,
        unsavedBadge: Color.lerp(a.unsavedBadge, b.unsavedBadge, t)!,
        neutralBadge: Color.lerp(a.neutralBadge, b.neutralBadge, t)!,
        linkColor: Color.lerp(a.linkColor, b.linkColor, t)!,
        selection: Color.lerp(a.selection, b.selection, t)!,
        blockquoteBar: Color.lerp(a.blockquoteBar, b.blockquoteBar, t)!,
        eraserFill: Color.lerp(a.eraserFill, b.eraserFill, t)!,
        eraserStroke: Color.lerp(a.eraserStroke, b.eraserStroke, t)!,
        penDefault: Color.lerp(a.penDefault, b.penDefault, t)!,
      );

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is EditorColors &&
        insertMode == other.insertMode &&
        normalMode == other.normalMode &&
        analysisMode == other.analysisMode &&
        analysisBlock == other.analysisBlock &&
        modeBadgeInsert == other.modeBadgeInsert &&
        modeBadgeNormal == other.modeBadgeNormal &&
        modeBadgeAnalysis == other.modeBadgeAnalysis &&
        pageBorder == other.pageBorder &&
        pageShadow == other.pageShadow &&
        pageShadowSoft == other.pageShadowSoft &&
        staleTint == other.staleTint &&
        analysisTint == other.analysisTint &&
        staleBadge == other.staleBadge &&
        analysisBadge == other.analysisBadge &&
        savedBadge == other.savedBadge &&
        unsavedBadge == other.unsavedBadge &&
        neutralBadge == other.neutralBadge &&
        linkColor == other.linkColor &&
        selection == other.selection &&
        blockquoteBar == other.blockquoteBar &&
        eraserFill == other.eraserFill &&
        eraserStroke == other.eraserStroke &&
        penDefault == other.penDefault;
  }

  @override
  int get hashCode => Object.hashAll([
    insertMode,
    normalMode,
    analysisMode,
    analysisBlock,
    modeBadgeInsert,
    modeBadgeNormal,
    modeBadgeAnalysis,
    pageBorder,
    pageShadow,
    pageShadowSoft,
    staleTint,
    analysisTint,
    staleBadge,
    analysisBadge,
    savedBadge,
    unsavedBadge,
    neutralBadge,
    linkColor,
    selection,
    blockquoteBar,
    eraserFill,
    eraserStroke,
    penDefault,
  ]);

  /// Every token in this group, by name.
  /// ///
  /// /// Used by the theming tests to prove [copyWith] touches only the field
  /// /// it was given, and handy for dumping or diffing a palette.
  Map<String, Color> get asMap => {
    'insertMode': insertMode,
    'normalMode': normalMode,
    'analysisMode': analysisMode,
    'analysisBlock': analysisBlock,
    'modeBadgeInsert': modeBadgeInsert,
    'modeBadgeNormal': modeBadgeNormal,
    'modeBadgeAnalysis': modeBadgeAnalysis,
    'pageBorder': pageBorder,
    'pageShadow': pageShadow,
    'pageShadowSoft': pageShadowSoft,
    'staleTint': staleTint,
    'analysisTint': analysisTint,
    'staleBadge': staleBadge,
    'analysisBadge': analysisBadge,
    'savedBadge': savedBadge,
    'unsavedBadge': unsavedBadge,
    'neutralBadge': neutralBadge,
    'linkColor': linkColor,
    'selection': selection,
    'blockquoteBar': blockquoteBar,
    'eraserFill': eraserFill,
    'eraserStroke': eraserStroke,
    'penDefault': penDefault,
  };
}

/// Radial tool dial chrome. The wheel's own colour *palette* is user data
/// /// (EditorSettingsStore), not theming — only the dial's furniture lives here.
@immutable
class DialColors {
  const DialColors({
    required this.accent,
    required this.hubFill,
    required this.hubStroke,
    required this.selectedWash,
    required this.chipIdle,
    required this.chipIdleIcon,
    required this.knobFill,
    required this.centerStroke,
    required this.swatchOutline,
    required this.eraserCenter,
    required this.previewFg,
    required this.previewBg,
    required this.labelMuted,
    required this.handleIdle,
  });

  /// Active arc, selected chip, size ring.
  final Color accent;

  /// Hub disc backing.
  final Color hubFill;

  /// Hairline around the hub.
  final Color hubStroke;

  /// Wash behind the selected tool chip.
  final Color selectedWash;

  /// Unselected tool chip fill.
  final Color chipIdle;

  /// Unselected tool chip glyph.
  final Color chipIdleIcon;

  /// Size-ring knob fill.
  final Color knobFill;

  /// Ring around the centre colour disc.
  final Color centerStroke;

  /// Outline marking the active swatch.
  final Color swatchOutline;

  /// Centre disc while the eraser is active.
  final Color eraserCenter;

  /// Stroke-preview text.
  final Color previewFg;

  /// Stroke-preview backing.
  final Color previewBg;

  /// Hex labels and the empty-wheel hint.
  final Color labelMuted;

  /// Readonly slider and toggle borders.
  final Color handleIdle;

  DialColors copyWith({
    Color? accent,
    Color? hubFill,
    Color? hubStroke,
    Color? selectedWash,
    Color? chipIdle,
    Color? chipIdleIcon,
    Color? knobFill,
    Color? centerStroke,
    Color? swatchOutline,
    Color? eraserCenter,
    Color? previewFg,
    Color? previewBg,
    Color? labelMuted,
    Color? handleIdle,
  }) => DialColors(
    accent: accent ?? this.accent,
    hubFill: hubFill ?? this.hubFill,
    hubStroke: hubStroke ?? this.hubStroke,
    selectedWash: selectedWash ?? this.selectedWash,
    chipIdle: chipIdle ?? this.chipIdle,
    chipIdleIcon: chipIdleIcon ?? this.chipIdleIcon,
    knobFill: knobFill ?? this.knobFill,
    centerStroke: centerStroke ?? this.centerStroke,
    swatchOutline: swatchOutline ?? this.swatchOutline,
    eraserCenter: eraserCenter ?? this.eraserCenter,
    previewFg: previewFg ?? this.previewFg,
    previewBg: previewBg ?? this.previewBg,
    labelMuted: labelMuted ?? this.labelMuted,
    handleIdle: handleIdle ?? this.handleIdle,
  );

  static DialColors lerp(DialColors a, DialColors b, double t) => DialColors(
    accent: Color.lerp(a.accent, b.accent, t)!,
    hubFill: Color.lerp(a.hubFill, b.hubFill, t)!,
    hubStroke: Color.lerp(a.hubStroke, b.hubStroke, t)!,
    selectedWash: Color.lerp(a.selectedWash, b.selectedWash, t)!,
    chipIdle: Color.lerp(a.chipIdle, b.chipIdle, t)!,
    chipIdleIcon: Color.lerp(a.chipIdleIcon, b.chipIdleIcon, t)!,
    knobFill: Color.lerp(a.knobFill, b.knobFill, t)!,
    centerStroke: Color.lerp(a.centerStroke, b.centerStroke, t)!,
    swatchOutline: Color.lerp(a.swatchOutline, b.swatchOutline, t)!,
    eraserCenter: Color.lerp(a.eraserCenter, b.eraserCenter, t)!,
    previewFg: Color.lerp(a.previewFg, b.previewFg, t)!,
    previewBg: Color.lerp(a.previewBg, b.previewBg, t)!,
    labelMuted: Color.lerp(a.labelMuted, b.labelMuted, t)!,
    handleIdle: Color.lerp(a.handleIdle, b.handleIdle, t)!,
  );

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is DialColors &&
        accent == other.accent &&
        hubFill == other.hubFill &&
        hubStroke == other.hubStroke &&
        selectedWash == other.selectedWash &&
        chipIdle == other.chipIdle &&
        chipIdleIcon == other.chipIdleIcon &&
        knobFill == other.knobFill &&
        centerStroke == other.centerStroke &&
        swatchOutline == other.swatchOutline &&
        eraserCenter == other.eraserCenter &&
        previewFg == other.previewFg &&
        previewBg == other.previewBg &&
        labelMuted == other.labelMuted &&
        handleIdle == other.handleIdle;
  }

  @override
  int get hashCode => Object.hashAll([
    accent,
    hubFill,
    hubStroke,
    selectedWash,
    chipIdle,
    chipIdleIcon,
    knobFill,
    centerStroke,
    swatchOutline,
    eraserCenter,
    previewFg,
    previewBg,
    labelMuted,
    handleIdle,
  ]);

  /// Every token in this group, by name.
  /// ///
  /// /// Used by the theming tests to prove [copyWith] touches only the field
  /// /// it was given, and handy for dumping or diffing a palette.
  Map<String, Color> get asMap => {
    'accent': accent,
    'hubFill': hubFill,
    'hubStroke': hubStroke,
    'selectedWash': selectedWash,
    'chipIdle': chipIdle,
    'chipIdleIcon': chipIdleIcon,
    'knobFill': knobFill,
    'centerStroke': centerStroke,
    'swatchOutline': swatchOutline,
    'eraserCenter': eraserCenter,
    'previewFg': previewFg,
    'previewBg': previewBg,
    'labelMuted': labelMuted,
    'handleIdle': handleIdle,
  };
}

/// Study-plan gantt: phase progression, week states, and task-type coding.
@immutable
class GanttColors {
  const GanttColors({
    required this.current,
    required this.nextUp,
    required this.upcoming,
    required this.todayMarker,
    required this.weekComplete,
    required this.weekActive,
    required this.weekUpcoming,
    required this.taskStudy,
    required this.taskPractice,
    required this.taskBuild,
    required this.taskReview,
    required this.taskMilestone,
    required this.checkpoint,
    required this.topicTag,
    required this.onTask,
    required this.tagWash,
    required this.tagBorder,
    required this.todayWash,
    required this.archived,
    required this.completed,
  });

  /// The phase currently being worked.
  final Color current;

  /// The phase queued behind [current].
  final Color nextUp;

  /// Every phase not yet started.
  final Color upcoming;

  /// The today line and its handle.
  final Color todayMarker;

  /// A completed week cell.
  final Color weekComplete;

  /// The in-flight week cell.
  final Color weekActive;

  /// A future week cell.
  final Color weekUpcoming;

  /// Task type: study.
  final Color taskStudy;

  /// Task type: practice.
  final Color taskPractice;

  /// Task type: build.
  final Color taskBuild;

  /// Task type: review.
  final Color taskReview;

  /// Task type: milestone check.
  final Color taskMilestone;

  /// Month-marker checkpoint tag.
  final Color checkpoint;

  /// Free-form topic tag.
  final Color topicTag;

  /// Content drawn on a filled task bar.
  final Color onTask;

  /// Base for a tag's 10% background wash.
  final Color tagWash;

  /// Base for a tag's 35% border wash.
  final Color tagBorder;

  /// Base for the 'Today' chip wash.
  final Color todayWash;

  /// An archived plan.
  final Color archived;

  /// A completed plan in the portfolio view.
  final Color completed;

  GanttColors copyWith({
    Color? current,
    Color? nextUp,
    Color? upcoming,
    Color? todayMarker,
    Color? weekComplete,
    Color? weekActive,
    Color? weekUpcoming,
    Color? taskStudy,
    Color? taskPractice,
    Color? taskBuild,
    Color? taskReview,
    Color? taskMilestone,
    Color? checkpoint,
    Color? topicTag,
    Color? onTask,
    Color? tagWash,
    Color? tagBorder,
    Color? todayWash,
    Color? archived,
    Color? completed,
  }) => GanttColors(
    current: current ?? this.current,
    nextUp: nextUp ?? this.nextUp,
    upcoming: upcoming ?? this.upcoming,
    todayMarker: todayMarker ?? this.todayMarker,
    weekComplete: weekComplete ?? this.weekComplete,
    weekActive: weekActive ?? this.weekActive,
    weekUpcoming: weekUpcoming ?? this.weekUpcoming,
    taskStudy: taskStudy ?? this.taskStudy,
    taskPractice: taskPractice ?? this.taskPractice,
    taskBuild: taskBuild ?? this.taskBuild,
    taskReview: taskReview ?? this.taskReview,
    taskMilestone: taskMilestone ?? this.taskMilestone,
    checkpoint: checkpoint ?? this.checkpoint,
    topicTag: topicTag ?? this.topicTag,
    onTask: onTask ?? this.onTask,
    tagWash: tagWash ?? this.tagWash,
    tagBorder: tagBorder ?? this.tagBorder,
    todayWash: todayWash ?? this.todayWash,
    archived: archived ?? this.archived,
    completed: completed ?? this.completed,
  );

  static GanttColors lerp(GanttColors a, GanttColors b, double t) =>
      GanttColors(
        current: Color.lerp(a.current, b.current, t)!,
        nextUp: Color.lerp(a.nextUp, b.nextUp, t)!,
        upcoming: Color.lerp(a.upcoming, b.upcoming, t)!,
        todayMarker: Color.lerp(a.todayMarker, b.todayMarker, t)!,
        weekComplete: Color.lerp(a.weekComplete, b.weekComplete, t)!,
        weekActive: Color.lerp(a.weekActive, b.weekActive, t)!,
        weekUpcoming: Color.lerp(a.weekUpcoming, b.weekUpcoming, t)!,
        taskStudy: Color.lerp(a.taskStudy, b.taskStudy, t)!,
        taskPractice: Color.lerp(a.taskPractice, b.taskPractice, t)!,
        taskBuild: Color.lerp(a.taskBuild, b.taskBuild, t)!,
        taskReview: Color.lerp(a.taskReview, b.taskReview, t)!,
        taskMilestone: Color.lerp(a.taskMilestone, b.taskMilestone, t)!,
        checkpoint: Color.lerp(a.checkpoint, b.checkpoint, t)!,
        topicTag: Color.lerp(a.topicTag, b.topicTag, t)!,
        onTask: Color.lerp(a.onTask, b.onTask, t)!,
        tagWash: Color.lerp(a.tagWash, b.tagWash, t)!,
        tagBorder: Color.lerp(a.tagBorder, b.tagBorder, t)!,
        todayWash: Color.lerp(a.todayWash, b.todayWash, t)!,
        archived: Color.lerp(a.archived, b.archived, t)!,
        completed: Color.lerp(a.completed, b.completed, t)!,
      );

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is GanttColors &&
        current == other.current &&
        nextUp == other.nextUp &&
        upcoming == other.upcoming &&
        todayMarker == other.todayMarker &&
        weekComplete == other.weekComplete &&
        weekActive == other.weekActive &&
        weekUpcoming == other.weekUpcoming &&
        taskStudy == other.taskStudy &&
        taskPractice == other.taskPractice &&
        taskBuild == other.taskBuild &&
        taskReview == other.taskReview &&
        taskMilestone == other.taskMilestone &&
        checkpoint == other.checkpoint &&
        topicTag == other.topicTag &&
        onTask == other.onTask &&
        tagWash == other.tagWash &&
        tagBorder == other.tagBorder &&
        todayWash == other.todayWash &&
        archived == other.archived &&
        completed == other.completed;
  }

  @override
  int get hashCode => Object.hashAll([
    current,
    nextUp,
    upcoming,
    todayMarker,
    weekComplete,
    weekActive,
    weekUpcoming,
    taskStudy,
    taskPractice,
    taskBuild,
    taskReview,
    taskMilestone,
    checkpoint,
    topicTag,
    onTask,
    tagWash,
    tagBorder,
    todayWash,
    archived,
    completed,
  ]);

  /// Every token in this group, by name.
  /// ///
  /// /// Used by the theming tests to prove [copyWith] touches only the field
  /// /// it was given, and handy for dumping or diffing a palette.
  Map<String, Color> get asMap => {
    'current': current,
    'nextUp': nextUp,
    'upcoming': upcoming,
    'todayMarker': todayMarker,
    'weekComplete': weekComplete,
    'weekActive': weekActive,
    'weekUpcoming': weekUpcoming,
    'taskStudy': taskStudy,
    'taskPractice': taskPractice,
    'taskBuild': taskBuild,
    'taskReview': taskReview,
    'taskMilestone': taskMilestone,
    'checkpoint': checkpoint,
    'topicTag': topicTag,
    'onTask': onTask,
    'tagWash': tagWash,
    'tagBorder': tagBorder,
    'todayWash': todayWash,
    'archived': archived,
    'completed': completed,
  };
}

/// Engram completion UI: spaced-repetition grading and answer feedback.
@immutable
class QuizColors {
  const QuizColors({
    required this.rateAgain,
    required this.rateHard,
    required this.rateGood,
    required this.rateEasy,
    required this.correctSurface,
    required this.correctStrong,
    required this.incorrectSurface,
    required this.incorrectStrong,
    required this.selectedSurface,
    required this.pendingSurface,
    required this.pendingStrong,
    required this.flippedSurface,
    required this.cardBorder,
    required this.gradedSurface,
  });

  /// Grade: again.
  final Color rateAgain;

  /// Grade: hard.
  final Color rateHard;

  /// Grade: good.
  final Color rateGood;

  /// Grade: easy.
  final Color rateEasy;

  /// Correct-answer tile and result card.
  final Color correctSurface;

  /// Correct-answer icon and label.
  final Color correctStrong;

  /// Wrong-answer tile and result card.
  final Color incorrectSurface;

  /// Wrong-answer icon and label.
  final Color incorrectStrong;

  /// A selected but ungraded option.
  final Color selectedSurface;

  /// Queued / awaiting-grade card.
  final Color pendingSurface;

  /// Queued icon and label.
  final Color pendingStrong;

  /// Flashcard back face.
  final Color flippedSurface;

  /// Flashcard hairline.
  final Color cardBorder;

  /// Card body once an attempt is graded.
  final Color gradedSurface;

  QuizColors copyWith({
    Color? rateAgain,
    Color? rateHard,
    Color? rateGood,
    Color? rateEasy,
    Color? correctSurface,
    Color? correctStrong,
    Color? incorrectSurface,
    Color? incorrectStrong,
    Color? selectedSurface,
    Color? pendingSurface,
    Color? pendingStrong,
    Color? flippedSurface,
    Color? cardBorder,
    Color? gradedSurface,
  }) => QuizColors(
    rateAgain: rateAgain ?? this.rateAgain,
    rateHard: rateHard ?? this.rateHard,
    rateGood: rateGood ?? this.rateGood,
    rateEasy: rateEasy ?? this.rateEasy,
    correctSurface: correctSurface ?? this.correctSurface,
    correctStrong: correctStrong ?? this.correctStrong,
    incorrectSurface: incorrectSurface ?? this.incorrectSurface,
    incorrectStrong: incorrectStrong ?? this.incorrectStrong,
    selectedSurface: selectedSurface ?? this.selectedSurface,
    pendingSurface: pendingSurface ?? this.pendingSurface,
    pendingStrong: pendingStrong ?? this.pendingStrong,
    flippedSurface: flippedSurface ?? this.flippedSurface,
    cardBorder: cardBorder ?? this.cardBorder,
    gradedSurface: gradedSurface ?? this.gradedSurface,
  );

  static QuizColors lerp(QuizColors a, QuizColors b, double t) => QuizColors(
    rateAgain: Color.lerp(a.rateAgain, b.rateAgain, t)!,
    rateHard: Color.lerp(a.rateHard, b.rateHard, t)!,
    rateGood: Color.lerp(a.rateGood, b.rateGood, t)!,
    rateEasy: Color.lerp(a.rateEasy, b.rateEasy, t)!,
    correctSurface: Color.lerp(a.correctSurface, b.correctSurface, t)!,
    correctStrong: Color.lerp(a.correctStrong, b.correctStrong, t)!,
    incorrectSurface: Color.lerp(a.incorrectSurface, b.incorrectSurface, t)!,
    incorrectStrong: Color.lerp(a.incorrectStrong, b.incorrectStrong, t)!,
    selectedSurface: Color.lerp(a.selectedSurface, b.selectedSurface, t)!,
    pendingSurface: Color.lerp(a.pendingSurface, b.pendingSurface, t)!,
    pendingStrong: Color.lerp(a.pendingStrong, b.pendingStrong, t)!,
    flippedSurface: Color.lerp(a.flippedSurface, b.flippedSurface, t)!,
    cardBorder: Color.lerp(a.cardBorder, b.cardBorder, t)!,
    gradedSurface: Color.lerp(a.gradedSurface, b.gradedSurface, t)!,
  );

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is QuizColors &&
        rateAgain == other.rateAgain &&
        rateHard == other.rateHard &&
        rateGood == other.rateGood &&
        rateEasy == other.rateEasy &&
        correctSurface == other.correctSurface &&
        correctStrong == other.correctStrong &&
        incorrectSurface == other.incorrectSurface &&
        incorrectStrong == other.incorrectStrong &&
        selectedSurface == other.selectedSurface &&
        pendingSurface == other.pendingSurface &&
        pendingStrong == other.pendingStrong &&
        flippedSurface == other.flippedSurface &&
        cardBorder == other.cardBorder &&
        gradedSurface == other.gradedSurface;
  }

  @override
  int get hashCode => Object.hashAll([
    rateAgain,
    rateHard,
    rateGood,
    rateEasy,
    correctSurface,
    correctStrong,
    incorrectSurface,
    incorrectStrong,
    selectedSurface,
    pendingSurface,
    pendingStrong,
    flippedSurface,
    cardBorder,
    gradedSurface,
  ]);

  /// Every token in this group, by name.
  /// ///
  /// /// Used by the theming tests to prove [copyWith] touches only the field
  /// /// it was given, and handy for dumping or diffing a palette.
  Map<String, Color> get asMap => {
    'rateAgain': rateAgain,
    'rateHard': rateHard,
    'rateGood': rateGood,
    'rateEasy': rateEasy,
    'correctSurface': correctSurface,
    'correctStrong': correctStrong,
    'incorrectSurface': incorrectSurface,
    'incorrectStrong': incorrectStrong,
    'selectedSurface': selectedSurface,
    'pendingSurface': pendingSurface,
    'pendingStrong': pendingStrong,
    'flippedSurface': flippedSurface,
    'cardBorder': cardBorder,
    'gradedSurface': gradedSurface,
  };
}
